const extraNames={radius:'Radius',elevation:'Elevation',motion:'Motion','z-index':'Z-index','breakpoints-grid':'Breakpoints & grid','borders-opacity':'Borders & opacity','focus-accessibility':'Focus & accessibility'};
const extraSelection={};
const extraOptions=()=>OPTIONS.filter(o=>o.foundation===foundation);
const selectedExtra=()=>extraOptions().find(o=>o.option===extraSelection[foundation])??extraOptions()[0];
function foundationDemo(o){
 const f=o.foundation;
 if(f==='radius')return `<div class="foundation-cards">${Object.entries(o.roles).map(([r,n])=>`<div class="radius-card" style="border-radius:var(${esc(n)})"><strong>${esc(r)}</strong><span>${esc(o.tokens[n].value)} / ${o.tokens[n].px}px</span></div>`).join('')}</div><p class="hint">Small controls → cards → large panels. Full rounding is reserved for pills.</p>`;
 if(f==='elevation')return `<div class="foundation-cards elevation-cards">${Object.entries(o.roles).map(([r,n])=>`<div style="box-shadow:var(${esc(n)});border:var(--ds-elevation-edge-${r}) solid var(--ds-elevation-edge-color)"><strong>${esc(r)}</strong><p>Example DS surface</p><small>${esc(o.tokens[n].value)}</small></div>`).join('')}</div><p class="hint">Named surfaces, not working overlays. Borders remain when shadows are hard to see.</p>`;
 if(f==='motion'){const id='reduce-'+serial++;return `<div class="motion-demo"><p>Toggle the state to compare timing. The value changes immediately; movement is optional.</p><label><input type="checkbox" data-reduce id="${id}"> Simulate reduced motion</label><button type="button" data-motion-toggle aria-pressed="false">Toggle example state</button><div class="motion-track"><div class="motion-target">Ready</div></div><p class="hint" data-motion-readout>${esc(o.tokens['--ds-motion-standard'].value)} standard · OS reduction always takes priority</p></div>`;}
 if(f==='z-index')return `<div class="stack-demo" aria-label="Illustrative shared stacking context">${Object.entries(o.roles).map(([r,n],i)=>`<div style="z-index:var(${esc(n)});inset-inline-start:${i*12}px;top:${i*30}px">${esc(r)} · ${esc(o.tokens[n].value)}</div>`).join('')}</div><p class="hint">Local stack only. Native dialogs in the browser top layer are outside this ordering.</p>`;
 if(f==='breakpoints-grid'){const id='grid-'+serial++;return `<label class="grid-control" for="${id}">Example viewport width <input type="range" id="${id}" min="320" max="1600" step="16" value="640" data-grid-width></label><p class="hint" data-grid-readout>640px · ${o.columns[o.native.breakpoints.filter(n=>640>=n).length]} columns</p><div class="grid-scroll" tabindex="0" aria-label="Grid preview; scroll horizontally for wide containers"><div class="grid-viewport" data-grid-viewport style="width:640px"><div class="grid-stage" data-grid-stage style="grid-template-columns:repeat(${o.columns[o.native.breakpoints.filter(n=>640>=n).length]},minmax(0,1fr))">${Array.from({length:12},(_,i)=>`<div>Item ${i+1}</div>`).join('')}</div></div></div><p class="hint">The width control previews a viewport; the inner grid respects its maximum width. Ship the generated numeric media-query recipe; CSS var() cannot supply query conditions.</p>`;}
 if(f==='borders-opacity')return `<div class="foundation-cards">${['hairline','strong','emphasis'].map(r=>`<div style="border:var(--ds-border-${r}) solid var(--edge)"><strong>${r}</strong><p>${o.tokens['--ds-border-'+r].px}px at the reference root</p></div>`).join('')}</div><div class="border-styles">${['solid','dashed','dotted'].map(r=>`<div style="border-block-start:var(--ds-border-strong) var(--ds-border-style-${r}) var(--edge)">${r}</div>`).join('')}</div><button disabled style="opacity:var(--ds-opacity-disabled)">Unavailable example</button><div class="opacity-demo"><span>Separate scrim layer</span><i style="opacity:var(--ds-opacity-overlay)"></i></div><p class="hint">Disabled is an actual disabled control. Do not apply reduced opacity to readable active content.</p>`;
 if(f==='focus-accessibility')return `<p>Use Tab to reach each control. Both ring colours are checked against both modes; the alternate is a choice, not a second ring that hides a failure.</p><div class="focus-surfaces">${['light','dark'].map(mode=>`<section class="focus-surface" style="background:var(--ds-focus-surface-${mode});color:${mode==='light'?'#111':'#fff'}"><h4>${mode} surface</h4><button class="focus-example" type="button">Primary ring · ${mode}</button><button class="focus-example alternate" type="button">Alternate ring · ${mode}</button></section>`).join('')}</div><p class="hint">2px outline · 2px offset · 44px minimum target. Forced-colours retains a system-colour outline. No focus animation.</p>`;
 return '';
}
function foundationScale(o){return foundationDemo(o)+`<div class="foundation-values">${Object.entries(o.tokens).map(([n,t])=>`<div><code>${esc(n)}</code><strong>${esc(t.value)}</strong><small>${t.px===undefined?'':`${t.px}px reference · `}${esc(t.derivation)}</small></div>`).join('')}</div>`;}
function bindFoundationDemos(){
 for(const sample of document.querySelectorAll('[data-foundation-option]:not([data-foundation-option=""])')){
  const o=OPTIONS.find(o=>`${o.foundation}/${o.option}`===sample.dataset.foundationOption);
  for(const [n,t] of Object.entries(o.tokens))sample.style.setProperty(n,t.value);
  sample.querySelector('[data-motion-toggle]')?.addEventListener('click',e=>{const active=e.currentTarget.getAttribute('aria-pressed')!=='true';e.currentTarget.setAttribute('aria-pressed',String(active));const target=sample.querySelector('.motion-target');target.dataset.active=String(active);target.textContent=active?'Selected':'Ready';});
  sample.querySelector('[data-reduce]')?.addEventListener('change',e=>{sample.dataset.reduced=String(e.target.checked);});
  sample.querySelector('[data-grid-width]')?.addEventListener('input',e=>{const width=Number(e.target.value),cols=o.columns[o.native.breakpoints.filter(n=>width>=n).length];const stage=sample.querySelector('[data-grid-stage]');sample.querySelector('[data-grid-viewport]').style.width=`${width}px`;stage.style.gridTemplateColumns=`repeat(${cols},minmax(0,1fr))`;sample.querySelector('[data-grid-readout]').textContent=`${width}px · ${cols} columns`;});
 }
}
